image: alpine

variables:
  COMMIT: ${CI_COMMIT_SHA}
  REGISTRY_REPO: registry.gitlab.com/gusisoft/onelike/client/social-service
  SOCIAL: social
  SOCIAL_DB: social-db
  SWAGGER: social-swagger

stages:
  - tests
  - registry
  - cleanup
  - deploy

Testing:
  stage: tests
  only:
    - devel
  before_script:
    - sudo git clean -ffdx
  script:
    - docker-compose -f docker-compose-dev.yml up -d --build
    - docker-compose -f docker-compose-dev.yml run social python manage.py recreate-db
    - docker-compose -f docker-compose-dev.yml run social flake8 project
    - docker-compose -f docker-compose-dev.yml run social python manage.py cov
  after_script:
    - docker-compose -f docker-compose-dev.yml down
    - sudo git clean -ffdx

Social Service:
  stage: registry
  only:
    - stage
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/client/social-service.git"
    - export SOCIAL_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}"
  script:
    - docker build $SOCIAL_REPO -t $SOCIAL:$COMMIT -f Dockerfile-stage
    - docker tag $SOCIAL:$COMMIT $REGISTRY_REPO/$SOCIAL:$TAG
    - docker push $REGISTRY_REPO/$SOCIAL:$TAG

Social DB:
  stage: registry
  only:
    - stage
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/client/social-service.git"
    - export SOCIAL_DB_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}:db"
  script:
    - docker build $SOCIAL_DB_REPO -t $SOCIAL_DB:$COMMIT -f Dockerfile
    - docker tag $SOCIAL_DB:$COMMIT $REGISTRY_REPO/$SOCIAL_DB:$TAG
    - docker push $REGISTRY_REPO/$SOCIAL_DB:$TAG

Social Swagger:
  stage: registry
  only:
    - stage
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/client/social-service.git"
    - export SWAGGER_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}:swagger"
  script:
    - docker build $SWAGGER_REPO -t $SWAGGER:$COMMIT -f Dockerfile
    - docker tag $SWAGGER:$COMMIT $REGISTRY_REPO/$SWAGGER:$TAG
    - docker push $REGISTRY_REPO/$SWAGGER:$TAG

Cleaning:
  stage: cleanup
  only:
    - stage
  script:
    - docker image rm -f $(docker image ls -q)

Stage:
  stage: deploy
  environment:
    name: stage
    url: http://stage.onelike.gusisoft.cl
  only:
    - stage
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - rm -rf ~/.ssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./stage-deploy.sh
