"""empty message

Revision ID: 5618209bde76
Revises: cc440b4b141b
Create Date: 2018-12-26 18:58:35.058250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5618209bde76'
down_revision = 'cc440b4b141b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_auth', schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_auth',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('social.facebook_auth_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('code_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('short_lived_access_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('short_lived_access_token_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='facebook_auth_pkey'),
    schema='social'
    )
    # ### end Alembic commands ###
