"""empty message

Revision ID: 7069cad5cd0b
Revises: dd22082eecbf
Create Date: 2019-06-12 01:17:47.178099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7069cad5cd0b'
down_revision = 'dd22082eecbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('brand_id', sa.Integer(), nullable=False, server_default="0"), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'brand_id', schema='social')
    # ### end Alembic commands ###
