"""empty message

Revision ID: 73ccebb31450
Revises: a017babbda1b
Create Date: 2019-01-09 14:56:19.335886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ccebb31450'
down_revision = 'a017babbda1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('additional', sa.Text(), nullable=True), schema='social')
    op.add_column('publications', sa.Column('title', sa.Text(), nullable=False), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'title', schema='social')
    op.drop_column('publications', 'additional', schema='social')
    # ### end Alembic commands ###
