"""empty message

Revision ID: 887b09149371
Revises: 73ccebb31450
Create Date: 2019-01-13 20:43:14.198769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887b09149371'
down_revision = '73ccebb31450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('link', sa.Text(), nullable=True), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'link', schema='social')
    # ### end Alembic commands ###
