"""empty message

Revision ID: a017babbda1b
Revises: 5618209bde76
Create Date: 2018-12-28 21:24:32.327534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a017babbda1b'
down_revision = '5618209bde76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('reject_reason', sa.Text(), nullable=True), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'reject_reason', schema='social')
    # ### end Alembic commands ###
