"""empty message

Revision ID: ae027ae0efa2
Revises: a4d2e52be5b2
Create Date: 2019-01-17 18:19:25.015615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae027ae0efa2'
down_revision = 'a4d2e52be5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('parent_id', sa.Integer(), nullable=True), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'parent_id', schema='social')
    # ### end Alembic commands ###
