"""empty message

Revision ID: cc440b4b141b
Revises: e6853cf8e576
Create Date: 2018-12-25 22:59:43.441581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc440b4b141b'
down_revision = 'e6853cf8e576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False), schema='social')
    op.alter_column('publications', 'status', server_default=None, schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'status', schema='social')
    # ### end Alembic commands ###
