"""empty message

Revision ID: dd22082eecbf
Revises: a458298434be
Create Date: 2019-01-27 14:22:48.679315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd22082eecbf'
down_revision = 'a458298434be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('category', sa.Text(), nullable=False), schema='social')
    op.add_column('publications', sa.Column('subcategory', sa.Text(), nullable=False), schema='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'subcategory', schema='social')
    op.drop_column('publications', 'category', schema='social')
    # ### end Alembic commands ###
